# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.1.1
  
workflows:
  upload-to-codecov:
    jobs:
      - node/test:
          post-steps:
            - codecov/upload
